export const GET_REQUEST_TO_CATEGORIES = "GET_REQUEST_TO_CATEGORIES";
export const DELETE_REQUEST_TO_CATEGORIES = "DELETE_REQUEST_TO_CATEGORIES";

export const GET_REQUEST_TO_PROMPTS = "GET_REQUEST_TO_PROMPTS";
export const DELETE_REQUEST_TO_PROMPT = "DELETE_REQUEST_TO_PROMPT"; 
