export const GET_REQUEST_TO_USER = "GET_REQUEST_TO_USER";
export const GET_REQUEST_TO_PRODUCTS = "GET_REQUEST_TO_PRODUCTS";
export const GET_REQUEST_TO_PRODUCT = "GET_REQUEST_TO_PRODUCT";
export const GET_REQUEST_TO_CARTS = "GET_REQUEST_TO_CARTS";
export const GET_REQUEST_TO_ORDERS = "GET_REQUEST_TO_ORDERS";

